parserOptions:
  project: './tsconfig.json'

ignorePatterns:
  - '**/*.test.ts'
  - 'build'

extends:
  - 'standard-with-typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'

rules:
  '@typescript-eslint/promise-function-async': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/consistent-type-assertions': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  'import/no-default-export': 'off'
