parserOptions:
  project: './tsconfig.json'

ignorePatterns:
  - '**/*.test.ts'
  - 'build'

extends:
  - 'standard-with-typescript'

rules:
  '@typescript-eslint/promise-function-async': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/consistent-type-assertions': 'off'