name: Unit testing

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build
        npm run test:unit
      env:
        CI: true
