name: Unit testing

on:
  push:
    paths-ignore:
    - 'docs/**'

jobs:
  test:
    name: node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CI: true

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Run unit tests
      run: npm run test:unit
